#!/bin/bash
#
# name:             sass-watch
# author:           Harold Bradley III
# email:            harold@bradleystudio.net
# created:          Fri 15 July 2013 11:53:35 AM EST
#
# description:      Watches sass files for modifications and compiles them
#
#                   This script assumes the sass files are in a directory named
#                   sass either in the current directory, in the parent
#                   directory, or in the parent's parent directory.
#
#                   Settings can be modified by creating a bash file named
#                   sass.config that is in the sass directory.
#
#                   Settings:
#                       $SASS_FILE - the main sass file to compile
#                       $STYLE_SHEET - the location of the stylesheet to compile
#                       $FLAGS - any flags to pass to sassc
#

# main() {{{1
#   main function
function main() {
    local SASS_DIR="$(pwd)/sass"
    if [[ ! -d "$SASS_DIR" ]] ; then
        local SASS_DIR="../sass"
        if [[ ! -d "$SASS_DIR" ]] ; then
            local SASS_DIR="../../sass"
        fi
    fi
    local SASS_FILE="$SASS_DIR/style.scss"
    local STYLE_SHEET="$SASS_DIR/../css/style.css"
    local FLAGS="-m"

    # Source sass.config if it exists
    if [[ -f "$SASS_DIR/sass.config" ]] ; then
        source "$SASS_DIR/sass.config"
    fi

    if [[ ! -d "$SASS_DIR" ]] ; then
        read -rsp "SASS directory not found. Press any key to continue...\n" -n1 key
    fi

    printf "        \e[0;32mRunning sass-watch \e[m \e[0;34m[sassc $FLAGS]\e[m\n"
    printf "            Watching for changes...\n"

    local LAST_MOD_TIME=0

    # Set up watches:
    inotifywait -qmr -e create,delete,modify,move --format "%f %e %T" --timefmt "%s" "./sass/" |
    while read filename event mod_time; do
        if [[ "${filename##*.}" == "scss" ]] ; then

            # Make sure at least 1 second has changed since last mod
            if [[ $LAST_MOD_TIME -ge $(($mod_time - 1)) ]] ; then continue ; fi

            # Otherwise, save this modtime and continue compiling:
            LAST_MOD_TIME=$mod_time

            # Set screen friendly event name
            case $event in
                'CREATE')
                    local event_name="Created:  "
                    ;;
                'DELETE')
                    local event_name="Deleted:  "
                    ;;
                'MOVE')
                    local event_name="Moved:    "
                    ;;
                'MODIFY')
                    local event_name="Modified: "
                    ;;
                *)
                    local event_name="Modified: "
                    ;;
            esac

            printf "    \e[1;33m$event_name \e[m$filename%-30s"
            TIMEFORMAT="(%Rs)"
            time (
                local ERROR_MSG="$(sassc $SASS_FILE $STYLE_SHEET $FLAGS 2>&1 > /dev/null)"
                if [[  $ERROR_MSG == "" ]] ; then
                    printf "\e[0;32m[compiled]\e[m "
                else
                    printf "\n\e[0;31m $ERROR_MSG\e[m "
                fi
            )
        fi
    done
}
# }}}


    # Run sass-watch main function if called directly
if [[ $0 = */sass-watch ]] ; then
    main
fi

# vim:set ft=sh fdm=marker:
