#!/bin/bash
#
# name:             tmux-sass-watch
# author:           Harold Bradley III
# email:            harold@bradleystudio.net
# created:          Mon 18 July 2016 11:53:35 AM EST
#
# description:      Acts as a sass-watch pane toggle.
#                   When called from inside tmux, will either open a new pane
#                   running sass-watch or will close a currently running
#                   sass-watch pane.
#

source $(dirname $0)/tmux-split
[[ ! "$?" = "0" ]] && echo "[WARN] tmux-status-window not found." && exit

toggle_split "sass-watch" "site-watch"


# vim:set ft=sh fdm=marker:
