#!/bin/bash
#
# name:             tmux-site-watch
# author:           Harold Bradley III
# email:            harold@bradleystudio.net
# created:          Mon 18 July 2013 11:53:35 AM EST
#
# description:      Acts as a site-watch pane toggle.
#                   When called from inside tmux, will either open a new pane
#                   running site-watch or will close a currently running
#                   site-watch pane.
#

source $(dirname $0)/tmux-split
[[ ! "$?" = "0" ]] && echo "[WARN] tmux-status-window not found." && exit

toggle_split "site-watch" "sass-watch"


# vim:set ft=sh fdm=marker:
