#!/bin/bash
#
# name:             tmux-site-watch
# author:           Harold Bradley III
# email:            harold@bradleystudio.net
# created:          Mon 18 July 2013 11:53:35 AM EST
#
# description:      Acts as a site-watch pane toggle.
#                   When called from inside tmux, will either open a new pane
#                   running site-watch or will close a currently running
#                   site-watch pane.
#


if ((tmux list-panes -F "#{pane_start_command}" | grep ^site-watch$ )>/dev/null) ; then
    tmux send-keys -t $(tmux list-panes -F "#{pane_id} #{pane_start_command}" | grep site-watch$ | awk "{ print $1 }") C-c
else # Otherwise, it isn't yet running, start it:
    # If sass-watch is running, share the screen with it:
    if ((ps -o "%c" $(tmux list-panes -F "#{pane_pid}") | grep ^sass-watch$ )>/dev/null) ; then
        tmux select-pane -t bottom
        tmux split-window -c "$(tmux display-message -p -F "#{pane_current_path}" -t0)" -h "site-watch"
        tmux select-pane -U
    else # Otherwise, just be on the bottom:
        tmux split-window -c "$(tmux display-message -p -F "#{pane_current_path}" -t0)" -v -l 5 "site-watch"
        tmux select-pane -U
    fi
fi

# vim:set ft=sh fdm=marker:
