#!/bin/bash
#
# name:             tmux-sass-watch
# author:           Harold Bradley III
# email:            harold@bradleystudio.net
# created:          Mon 18 July 2013 11:53:35 AM EST
#
# description:      Acts as a sass-watch pane toggle.
#                   When called from inside tmux, will either open a new pane
#                   running sass-watch or will close a currently running
#                   sass-watch pane.
#

# Sanity check
if test `tmux -V | sed "s/[^0-9]//g"` -lt 19 ; then
    echo "Tmux-sass-watch doesn't support versions less than 1.9"; exit
fi


if ((tmux list-panes -F "#{pane_start_command}" | grep ^sass-watch$ )>/dev/null) ; then
    kill $(ps -o "%p%c" $(tmux list-panes -F "#{pane_pid}") | grep sass-watch$ | awk "{ print $1 }")
else # Otherwise, it isn't yet running, start it:
    # If site-watch is running, share the screen with it:
    if ((ps -o "%c" $(tmux list-panes -F "#{pane_pid}") | grep ^site-watch$ )>/dev/null) ; then
        tmux select-pane -t bottom
        tmux split-window -c "#{pane_current_path}" -h "sass-watch"
        tmux select-pane -U
    else # Otherwise, just be on the bottom:
        tmux split-window -c "#{pane_current_path}" -v -l 5 "sass-watch"
        tmux select-pane -U
    fi
fi

# vim:set ft=sh fdm=marker:
