#!/bin/bash
#
# name:             install
# author:           Harold Bradley III
# email:            harold@bradleystudio.net
# created:          12/21/2015
#
# description:      Creates a symlink in the home directory for each
#                   appropriate dotfile in this repo.
#

DOTFILES_ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source $DOTFILES_ROOT_DIR/.bash_lib/msg || { echo "'msg' does not exist!" >&2 ; exit 1; }

### creat_link()
# create_link() {{{1
function create_link() {
    echo "Linking $filename..."
    if [[ -d $DOTFILES_ROOT_DIR/$1 ]] ; then
        ln -s $DOTFILES_ROOT_DIR/$filename/ ~/$filename
    else
        ln -s $DOTFILES_ROOT_DIR/$filename ~/$filename
    fi
} # }}}

# Setup links
for file in $DOTFILES_ROOT_DIR/.[^.]* ; do
    filename=${file##*/}
    if [[ $filename != '.git' ]] ; then
        if [[ -f ~/$filename || -d ~/$filename ]] ; then
            link=$(readlink ~/$filename)
            if [[ -L ~/$filename && ${link%/} == $DOTFILES_ROOT_DIR/$filename ]] ; then
                echo "Skipping $filename. Already linked."
                continue
            elif msg_ask "$filename already exists but does not link to dotfiles. Remove it?"; then
                rm -r ~/$filename
            fi
        fi
        create_link $filename
    fi
done

# Verify (correct) Permissions
echo "Checking Permissions..."
chown $USER:$USER $DOTFILES_ROOT_DIR/ -R
if [[ $? != 0 ]] ; then # If that didn't work, use sudo:
    sudo chown $USER:$USER $DOTFILES_ROOT_DIR/ -R
fi

# Setup git hooks
if [[ -d $DOTFILES_ROOT_DIR/.git/hooks ]] ; then
    if [[ -L $DOTFILES_ROOT_DIR/.git/hooks ]] ; then
        if [[ $(readlink $DOTFILES_ROOT_DIR/.git/hooks) == $DOTFILES_ROOT_DIR/hooks ]] ; then
            echo "Hooks already linked."
        elif msg_ask "A hooks link already exists but does not link to dotfiles hooks. Remove it?"; then
            rm $DOTFILES_ROOT_DIR/.git/hooks
            echo "Linking git hooks..."
            ln -s $DOTFILES_ROOT_DIR/hooks $DOTFILES_ROOT_DIR/.git/hooks
        fi
    elif msg_ask "A hooks directory already exists but does not link to dotfiles hooks. Remove it and use dotfiles hook?"; then
        rm -r $DOTFILES_ROOT_DIR/.git/hooks
        echo "Linking git hooks..."
        ln -s $DOTFILES_ROOT_DIR/hooks $DOTFILES_ROOT_DIR/.git/hooks
    fi
else
    echo "Linking git hooks..."
    ln -s $DOTFILES_ROOT_DIR/hooks $DOTFILES_ROOT_DIR/.git/hooks
fi

source ~/.bash_profile

# vim:set ft=sh fdm=marker:
