# -*- mode: ruby -*-
#
# name:             Vagrantfile
# author:           Harold Bradley III
# email:            harold@bradleystudio.net
# created:          01/11/2017
#
# description:      For a configuration reference, please see the online
#					documentation at https://docs.vagrantup.com.
#

Vagrant.configure("2") do |config|

  config.ssh.forward_agent = true  # Use ssh credentials from your host machine

  # Give 1/4 of the host's memory to the virtual machine
  config.vm.provider "virtualbox" do |v|
    host = RbConfig::CONFIG['host_os']

    # Cross-platform checks
    if host =~ /darwin/
      # sysctl returns Bytes and we need to convert to MB
      mem = `sysctl -n hw.memsize`.to_i / 1024
    elsif host =~ /linux/
      # meminfo shows KB and we need to convert to MB
      mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i
    elsif host =~ /mswin|mingw|cygwin/
      # Windows code via https://github.com/rdsubhas/vagrant-faster
      mem = `wmic computersystem Get TotalPhysicalMemory`.split[1].to_i / 1024
    end

    mem = mem / 1024 / 4
    v.customize ["modifyvm", :id, "--memory", mem]
  end

  # Personal Provisioning
  config.vm.provision :shell do |shell|
	shell.privileged = false
	shell.inline = "if [[ ! -d ~/.dotfiles ]] ; then touch ~/.ssh/known_hosts && ssh-keyscan -t rsa,dsa github.com 2>&1 | sort -u - ~/.ssh/known_hosts > ~/.ssh/tmp_hosts && mv ~/.ssh/tmp_hosts ~/.ssh/known_hosts && git clone git@github.com:hbradleyiii/dotfiles.git ~/.dotfiles && ~/.dotfiles/install ; fi"
  end

end

# vi: set ft=ruby:
