#!/bin/bash
#
# name:             dot.install
# author:           Harold Bradley III
# email:            harold@bradleystudio.net
# created:          04/11/2016
#
# description:      A git hook run when checking out a new branch.
#

# Allows us to read user input below, assigns stdin to keyboard
exec < /dev/tty

./install

type -P "ctags-exuberant" &>/dev/null
if [[ $? -eq 0 ]] ; then
    ctags-exuberant -eRf./tags --exclude=.git --exclude=.vim .[^.]?*
else
    echo 'ctags-exuberant is not installed. Skipping ctags.'
fi

exec <&-

# vim:set ft=sh fdm=marker:
