#!/bin/bash
#
# name:             dot.install
# author:           Harold Bradley III
# email:            harold@bradleystudio.net
# created:          04/11/2016
#
# description:      A git hook run when after merging.
#

# Allows us to read user input below, assigns stdin to keyboard
exec < /dev/tty

./install
ctags-exuberant -eRf./tags --exclude=.git --exclude=.vim .[^.]?*

exec <&-

# vim:set ft=sh fdm=marker:
